### ISSUE TITLE
Parameter type "gdal" does not work

### ISSUE THREAD

**Issue by kyawmyintthein** [fawick/go-mapnik#12]
This is my sample style.xml, it work shp file only.

<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">

  <Style name="color relief style">
    <Rule>
      <RasterSymbolizer />
    </Rule>
  </Style>

  <Style name="slopeshade style">
    <Rule>
      <RasterSymbolizer opacity="0.1" comp-op="multiply" scaling="bilinear" />
    </Rule>
  </Style> 

  <Style name="hillshade style">
    <Rule>
      <RasterSymbolizer opacity="0.6" comp-op="multiply" scaling="bilinear" />
    </Rule>
  </Style>

  <Style name="contours style">
    <Rule>
      <LineSymbolizer stroke="rgb(255,255,255)" stroke-width="1" />
    </Rule>
  </Style>

  <Layer name="color relief" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
    <StyleName>color relief style</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">data/S07E106_utm48s_relief.tif</Parameter>
    </Datasource>
  </Layer>

  <Layer name="slopeshade" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
    <StyleName>slopeshade style</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">data/S07E106_utm48s_slopeshade.tif</Parameter>
    </Datasource>
  </Layer>

  <Layer name="hillshade" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
    <StyleName>hillshade style</StyleName>
    <Datasource>
      <Parameter name="type">gdal</Parameter>
      <Parameter name="file">data/S07E106_utm48s_hs.tif</Parameter>
    </Datasource>
  </Layer> 

  <Layer name="contours" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
    <StyleName>contours style</StyleName>
    <Datasource>
      <Parameter name="type">shape</Parameter>
      <Parameter name="file">data/s07e106_25m.shp</Parameter>
    </Datasource>
  </Layer> 

</Map>

**Comment by fawick** [comment]
I'd assume that your mapnik shared library does not support raster graphics.

**Comment by kyawmyintthein** [comment]
I am very new in mapnik. So, how I can solve this problem. Do you have any suggestion.

**Comment by fawick** [comment]
Have you tried following the installation guide? https://github.com/mapnik/mapnik/wiki/Mapnik-Installation

**Comment by kyawmyintthein** [comment]
I am using Mac. I think I didn't follow that. Let me try. thanks.

**Comment by kyawmyintthein** [comment]
Thanks @fawick. It is work.
