### ISSUE TITLE
Add a Version()

### ISSUE THREAD

**Issue by erjoalgo** [fawick/go-mapnik#5]
Add a Version() function that shows exactly which mapnik version is linked.

**Comment by fawick** [comment]
github.com/omniscale/go-mapnik was brought to my attention. It offers mapnik version information and may serve as a surrogate until I can close this issue. Its API does differ slightly, though.

**Comment by fawick** [comment]
Quickfix branch available: https://github.com/fawick/go-mapnik/tree/issue-5-fix

**Comment by fawick** [comment]
Merged into master.
