### ISSUE TITLE
Provide bindings for loading stylesheet directly from a string, not from file

### ISSUE THREAD

**Issue by erjoalgo** [fawick/go-mapnik#6]
You currently only provide:
```func (m *Map) Load(stylesheet string) error ```, where "stylesheet" is read as a filename (the parameter name should make this more obvious). So there is no way to create a map from a dynamically-generated stylesheet. 

The python bindings provide a `mapnik.load_map_from_string` to accomplish this.

**Comment by fawick** [comment]
@erjoalgo I apologize for the long time I kept you waiting.I finally took the time to do an experimental branch for this issue: https://github.com/fawick/go-mapnik/tree/issue-6-fix. I wondered if you kindly would give it a try.

It is (similar to the rest of the package) lacking unit tests at the moment. I will add these later.

It currently uses my fork of the C API in which I added the missing function. If you happen to find it to be working out for you I will offer them to @springmeyer as a PR and merge this branch to master.

**Comment by rnix** [comment]
This worked well for me testing the code @erjoalgo wrote.

**Comment by erjoalgo** [comment]
@fawick I'm currently not able to try your branch directly, but based on @rnix's comment, I see your fix works well. Thanks for following up on this!

**Comment by fawick** [comment]
Merged into master.
